config/routes.rb
Rails.application.routes.draw do

  get 'braintree/new'
  root to: "welcome#index"

  get "/redirect_to_profile", to: "users#redirect_from_login"
  get '/listings/:id/verified' => "listings#verified", as: "verified_listing"

  resources :reservations
 
  resources :listings do 
     resources :reservations 
  end

  resources :users do 
     resources :reservations do
      resource :payment
  end
  end

  resources :search, controller: "search", only: [:index]

  resources :passwords, controller: "clearance/passwords", only: [:create, :new] 
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  # <%= link_to 'edit password', edit_user_password_path %>


  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  

  post "/users/:user_id/reservations/:reservation_id/checkout" => "payments#checkout", as: "payments_checkout"

  post "/users/:user_id/reservations/:reservation_id/confirmed" => "reservations#index", as: "reservations_confirmed"


   post '/search' => 'search#search'
  # constraints Clearance::Constraints::SignedIn.new { |user| user.admin? } do
  #   root to: "admin/dashboards#show", as: :admin_root
  # end

  # constraints Clearance::Constraints::SignedIn.new do
  #   root to: "dashboards#show", as: :signed_in_root
  # end

  # constraints Clearance::Constraints::SignedOut.new do
  #   root to: "marketing#index"
  # end

# devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }



end

app/models/listing.rb
class Listing < ApplicationRecord
	belongs_to :user
	self.per_page = 9
	has_attached_file :listing_img, styles: { listing_index: "700x700>", listing_show: "700x700>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :listing_img, content_type: /\Aimage\/.*\z/
  has_many :reservations, dependent: :delete_all

  WillPaginate.per_page = 9
  
  require 'pg_search'
  include PgSearch
  multisearchable :against => [ :name, :description, :city, :country ]

  
  scope :city, -> (city) { where( "city ILIKE :city", city: "%#{city}%" )}
  scope :price, -> (price) { where ( "price < ?" " #{price} ")}
  scope :bedrooms, -> (bedrooms) { where ( "bedrooms >= ?" " #{bedrooms}" )}
  scope :bathrooms, -> (bathrooms) { where ("bathrooms >= ?" " #{bathrooms}")} 




def self.search(search)
    where(['city iLIKE ?', "%#{search}%"])
end 

  def self.search_cities(query)
      where("city ILIKE :city", city: "%#{query}%") do |record|
        record.city
      end
    end
    
  def host
      if self.user_id == nil
        "Mystery house!"
      else
        User.find(self.user_id).first_name
      end
    end

# def self.search_by(search_term)
# 	where("LOWER(name) LIKE :search_term", 
# 	search_term: "%#{search_term.downcase}%")
# end

# def self.between_range(search_pricen_term, search_pricex_term)
# 	scope :between_range, -> (min,max){
# 		where("price >= ? AND price <= ?", min,max)
# 	}

# end



end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :find_listing, only: [:show, :edit, :update, :destroy, :verified]


def index
  if params[:search]
    @listings = Listing.search(params[:search])
    @listings = Listing.search(params[:search]).paginate(page: params[:page])
  else
    @listings = Listing.paginate(:page => params[:page])
   end 
end

# @listings = Listing.find(params[:id])
# @listings = Listing.paginate(:page => params[:page])
# @listings = Listing.paginate(:page => params[:pßage])
  # ## perform a paginated query:
  # @listing = Listing.paginate(:page => params[:page])
  # @listings = Listing.all.order("created_at DESC")

def new 
  @listing = current_user.listings.build
end 

def show
  authorize! :update, @listing 
end

def create
  @listing = current_user.listings.build(listing_params)
    if @listing.save
      redirect_to '/listings'
    else
      flash[:message] = "Listing was not created"
      render 'new'
    end
end

def edit 
  authorize! :update, @listing 
end 

def update 
  if @listing.update(listing_params)
    redirect_to listing_path(@listing)
  else 
    render "edit"
  end 
end

def destroy 
  @listing.destroy
  redirect_to '/listings'
end 


def verified 
  if current_user.admin?
    @listing.verify = true
    @listing.save
  else
    flash[:message] = "Sorry, you are not authorized"
  end 
  redirect_to listing_path(@listing)
end 


private 

  def listing_params
    params.require(:listing).permit(:name, :description, :address, :city, :state, :zipcode, :country, :property_type, :category, :listing_img, :verify, :price, :bedrooms, :bathrooms)
  end

  def find_listing
    @listing = Listing.find(params[:id])
  end

end 

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<%= simple_form_for(@listing, html: { class: 'form-inline' })do |f| %>

	<%= f.file_field :listing_img%>
	<%= f.input :price %>
	<%= f.input :name, label: "Listing Title" %>
	<%= f.input :bedrooms %>
	<%= f.input :bathrooms %>
	<%= f.input :description %>s
	<%= f.input :address %>
	<%= f.input :city %>
	<%= f.input :state %>
	<%= f.input :zipcode %>
	<%= f.select :country, options_for_select(Listing.country_list) %>
	<%= f.input :property_type %>
	<h3> Has which of the following? </h3>
	<%= f.input :category, label: "Pool"  %>
	<%= f.input :category, label: "Pets Allowed"  %>
	<%= f.input :category, label: "Washer/Dryer"  %>
	<%= f.input :category, label: "Balcony" %>
	<br/>
	<br/>
	<%= f.button :submit, :class => 'btn-custom' %>
<% end %>

app/views/listings/edit.html.erb
<h1> Edit this listing  </h1>

<%= render 'form' %>

app/views/listings/index.html.erb
<div class="d-flex justify-content-center flex-wrap" >
<h2 style="text-align:center">   <%= link_to "All Listings", listings_path %>  ||  <%= link_to "Add a New Listing", new_listing_path %> <br/> 

	<%= form_tag(listings_path, method: :get) do %>
  	City: <%= text_field_tag :search, params[:search] %>
<!--    	Price: <%= number_field_tag :search, params[:search] %> -->
   	<%= submit_tag "Search" %>
   <% end %> </h2> 
</div>
s

<div class="d-flex justify-content-center flex-wrap" >
	<% @listings.each do |listing| %>
	<a href="/listings/<%= listing.id %>">
<!-- 		<h2> Price: <%= listing.price %> </h2>  -->
	<h2> City: <%= listing.city %> </h2>
	<%= image_tag listing.listing_img.url(:listing_index), class: "listing" %>
	</a>
	<%end%>
</div>



	<div class="d-flex justify-content-center flex-wrap" >
	  <h3 > <%= will_paginate @listings %> </h3> 
	 </div>

app/views/listings/new.html.erb
<h1> Make a new listing here </h1>

<%= render 'form' %>

app/views/listings/show.html.erb
<h3> <%= link_to "Click Here to Make a Reservation for this Listing", new_listing_reservation_path(@listing.id) %> <br/></h3>

<h2> <%= @listing.name %> <h2>

<%= image_tag @listing.listing_img.url(:listing_index),  class: "listing_show"  %>

<p> Address: <%= @listing.address %> </p>
<p> Price: <%= @listing.price %> </p>
<p> Bedrooms: <%= @listing.bedrooms %> </p>
<p> Bathrooms: <%= @listing.bathrooms %> </p>
<p> Description: <%= @listing.description %> </p>
			<p> <%= @listing.city %> </p>
				<p> <%= @listing.state %> </p>
					<p> <%= @listing.zipcode %></p>
						<p> <%= @listing.country %></p>
							<p> <%= @listing.property_type %> </p>
								<p> <%= @listing.category %> </p>
									<p> Verificiation: <%= @listing.verify %> </p>

<%= link_to "Back", listings_path %>

<% if can? :update, @listing %>
	<%= link_to "Edit", edit_listing_path(@listing) %>
<% end %>

<% if can? :destroy, @listing %>
	<%= link_to "Delete", listing_path(@listing), method: :delete, data: {confirm: "Are you sure?"} %>
<% end %>

<% if current_user.admin == true  %>
	<%= link_to "Verify Listing", verified_listing_path(@listing) %>
<% end %>