config/routes.rb
Rails.application.routes.draw do

  get 'braintree/new'
  root to: "welcome#index"

  get "/redirect_to_profile", to: "users#redirect_from_login"
  get '/listings/:id/verified' => "listings#verified", as: "verified_listing"

  resources :reservations
 
  resources :listings do 
     resources :reservations 
  end

  resources :users do 
     resources :reservations do
      resource :payment
  end
  end

  resources :search, controller: "search", only: [:index]

  resources :passwords, controller: "clearance/passwords", only: [:create, :new] 
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  # <%= link_to 'edit password', edit_user_password_path %>


  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  

  post "/users/:user_id/reservations/:reservation_id/checkout" => "payments#checkout", as: "payments_checkout"

  post "/users/:user_id/reservations/:reservation_id/confirmed" => "reservations#index", as: "reservations_confirmed"


   post '/search' => 'search#search'
  # constraints Clearance::Constraints::SignedIn.new { |user| user.admin? } do
  #   root to: "admin/dashboards#show", as: :admin_root
  # end

  # constraints Clearance::Constraints::SignedIn.new do
  #   root to: "dashboards#show", as: :signed_in_root
  # end

  # constraints Clearance::Constraints::SignedOut.new do
  #   root to: "marketing#index"
  # end

# devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }



end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
  has_many :authentications, dependent: :destroy
  has_many :listings
  has_many :reservations
  has_attached_file :avatar, styles: {avatar_show: "300x300>", avatar_thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  validates :email, :presence => {message: "Email address cannot be blank."}, email: {message: "Please enter a valid email address."}, :on => :create
 

  # devise :omniauthable, omniauth_providers: [:google_oauth2]


 def self.create_with_auth_and_hash(authentication, auth_hash)
   user = self.create!(
     first_name: auth_hash["info"]["name"],
     last_name: auth_hash["info"]["name"],
     email: auth_hash["info"]["email"],
     password: SecureRandom.hex(10)
   )
   user.authentications << authentication
   return user
 end

 # grab google to access google for user data
 def google_token
   x = self.authentications.find_by(provider: 'google_oauth2')
   return x.token unless x.nil?
 end





# class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
#   def google_oauth2
#       # You need to implement the method below in your model (e.g. app/models/user.rb)
#       @user = User.from_omniauth(request.env['omniauth.auth'])

#       if @user.persisted?
#         flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
#         sign_in_and_redirect @user, event: :authentication
#       else
#         session['devise.google_data'] = request.env['omniauth.auth'].except(:extra) # Removing extra as it can overflow some session stores
#         redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
#       end
#   end
# end 

# def self.from_omniauth(access_token)
#     data = access_token.info
#     user = User.where(email: data['email']).first

#     # Uncomment the section below if you want users to be created if they don't exist
#     # unless user
#     #     user = User.create(name: data['name'],
#     #        email: data['email'],
#     #        password: Devise.friendly_token[0,20]
#     #     )
#     # end
#     user
# end

# end
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController

  before_action :find_user, only: [:show, :edit, :update, :destroy]

def redirect_from_login
  redirect_to user_path(current_user)
end

def new 
  @user = User.new
end 

def show
end

def create
    user = User.new(user_params)
    if user.save
      sign_in(user)
   
      redirect_to user_path(user.id)
  else
     flash[:message] = "User was not created"
    redirect_to sign_up_path
  end
end

def edit
end

def update 
  if @user.update(user_params)
    redirect_to user_path(@user)
  else 
    flash[:message] = "User was not updated"
    render "edit"
  end 
end


private 
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :avatar)
  end
  def find_user
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :first_name %>
  <%= form.text_field :first_name, type: 'first_name' %>
</div>

<div class="text-field">
  <%= form.label :last_name %>
  <%= form.text_field :last_name, type: 'last_name'%>
</div>


<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

app/views/users/create.js.erb
//remove old validation messages
$(".notice").remove();
 
//display new validation messages
<% @user.errors.each do |key, value| %>
$(“#helpBlock”).append(‘<div class=”notice”><%= escape_javascript(value)%></div>’);
<% end %>

app/views/users/edit.html.erb
<%= simple_form_for @user do |f| %>
  	<%= f.input :avatar, as: :file %>
	<%= f.input :first_name %>
	<%= f.input :last_name %>
	<%= f.input :email %>
	<%= f.input :password %>
	<%= f.button :submit, :class => 'btn-custom' %>
<% end %>

app/views/users/new.html.erb
<h1> Sign up for AirBnb </h1>

<div id="clearance" class="sign-up">

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>

    <span id="helpBlock" class="help-block"></span>
  <% end %>
</div>

app/views/users/show.html.erb
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {
  background: white;
}

.content {
  max-width: 900px;
  margin: auto;
  background: white;
  padding: 40px;
}
</style>
</head>


<div class="content">
<h1> Hi ! This is your profile page <%= @user.first_name %> </h1>

<%= image_tag @user.avatar.url(:avatar_show), class: "avatar" %>


<h3> <%= link_to "Click here", edit_user_path(@user) %> to edit your profile or to add an image  </a> </h3>

<h2> What would you like to do? </h2>


<h3> 1. See all <%= link_to "Listings", listings_path %> <br/>
2. Make a <%= link_to "New Listing", new_listing_path %> <br/>
3. Look at your <%= link_to "Pending & Confirmed Reservations", user_reservations_path(user_id: @user.id) %> <br/> </h3> <br/>

<h3> Here are all your active listings: </h3>



    <% user_listings = Listing.where(user_id: current_user.id) %>


    <% user_listings.each do |listing| %>
    	<div style=" display: inline-block">
	    <p><strong><%= listing.name %></strong></p>
		<%= image_tag listing.listing_img.url(:listing_index), class: "listing" %> <br/>
        <%= link_to "Edit this listing", edit_listing_path(listing) %>
      </div>

    <% end %>

  </div>

  