config/routes.rb
Rails.application.routes.draw do

  get 'braintree/new'
  root to: "welcome#index"

  get "/redirect_to_profile", to: "users#redirect_from_login"
  get '/listings/:id/verified' => "listings#verified", as: "verified_listing"

  resources :reservations
 
  resources :listings do 
     resources :reservations 
  end

  resources :users do 
     resources :reservations do
      resource :payment
  end
  end

  resources :search, controller: "search", only: [:index]

  resources :passwords, controller: "clearance/passwords", only: [:create, :new] 
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  # <%= link_to 'edit password', edit_user_password_path %>


  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  

  post "/users/:user_id/reservations/:reservation_id/checkout" => "payments#checkout", as: "payments_checkout"

  post "/users/:user_id/reservations/:reservation_id/confirmed" => "reservations#index", as: "reservations_confirmed"


   post '/search' => 'search#search'
  # constraints Clearance::Constraints::SignedIn.new { |user| user.admin? } do
  #   root to: "admin/dashboards#show", as: :admin_root
  # end

  # constraints Clearance::Constraints::SignedIn.new do
  #   root to: "dashboards#show", as: :signed_in_root
  # end

  # constraints Clearance::Constraints::SignedOut.new do
  #   root to: "marketing#index"
  # end

# devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }



end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController

def new
  @client_token = Braintree::ClientToken.generate
end

def checkout
  nonce_from_the_client = params[:checkout_form][:payment_method_nonce]
  @reservation = Reservation.find(params[:reservation_id])

  result = Braintree::Transaction.sale(
   :amount =>  @reservation.listing.price, 
   :payment_method_nonce => nonce_from_the_client,
   :options => {
      :submit_for_settlement => true
    }
   )

  if result.success?
    @reservation.confirmed = true
    @reservation.save
    redirect_to new_user_reservation_payment_path
    flash[:success] = "You are all confirmed!!"
  else
    redirect_to new_user_reservation_payment_path
    flash[:alert] = "Your payment did not go through, please try again"
  end
end


end

app/views/payments/new.html.erb
<h1>Payment Page </h1>


<div class="demo-frame">

  <%= form_for :checkout_form, url: payments_checkout_path, html: { id: "cardForm"} do |form| %>

    <%= form.label :card_number, "Credit Card Number", html: {class: "hosted-fields--label"} %>
    <div id="card-number" class="hosted-field"></div>

    <%= form.label :expiration_date, "Expiration Date", html: {class: "hosted-fields--label"} %>
    <div id="expiration-date" class="hosted-field"></div>

    <%= form.label :cvv, "CVV", html: {class: "hosted-fields--label"} %>
    <div id="cvv" class="hosted-field"></div>


    <%= form.hidden_field "payment_method_nonce" %>



    <div class="button-container">
      <%= form.submit "Purchase", disabled: false, class: "btn btn-primary", id: "submit-payment-btn" %>
    </div>

  <% end %>
</div>

<!-- Load the Client component. -->
<script src="https://js.braintreegateway.com/web/3.6.3/js/client.min.js"></script>

<!-- Load the Hosted Fields component. -->
<script src="https://js.braintreegateway.com/web/3.6.3/js/hosted-fields.min.js"></script> 


<script>

var form = document.querySelector('#cardForm');
var submit = document.querySelector("#submit-payment-btn");
var authorization = '<%= @client_token %>';

braintree.client.create({
  // Replace this with your own authorization.
  authorization: authorization
}, function (clientErr, clientInstance) {
  if (clientErr) {
    // Handle error in client creation
    return;
  }

  braintree.hostedFields.create({
    client: clientInstance,
    styles: {
      'input': {
        'font-size': '14pt'
      },
      'input.invalid': {
        'color': 'red'
      },
      'input.valid': {
        'color': 'green'
      }
    },
    fields: {
      number: {
        selector: '#card-number',
        placeholder: '4111 1111 1111 1111'
      },
      cvv: {
        selector: '#cvv',
        placeholder: '123'
      },
      expirationDate: {
        selector: '#expiration-date',
        placeholder: '10/2019'
      }
    }
  }, function (hostedFieldsErr, hostedFieldsInstance) {
    if (hostedFieldsErr) {
      console.error(hostedFieldsErr);
      return;
    }

    submit.removeAttribute('disabled');

    form.addEventListener('submit', function (event) {
     form.submit();

      hostedFieldsInstance.tokenize(function (tokenizeErr, payload) {
        if (tokenizeErr) {
         console.error(tokenizeErr);
          return;
        }

        // Put `payload.nonce` into the `payment_method_nonce` input, and then
        // submit the form. Alternatively, you could send the nonce to your server
        // with AJAX.
        document.querySelector('input[name="checkout_form[payment_method_nonce]"]').value = payload.nonce;
        form.submit();
      });
    }, false);
  });
});
</script>

app/views/payments/show.html.erb
yay you're confirmed! 